server:
  port: 8081
  servlet:
    context-path: /gsms
default:
  name: jinyannan
  age: 47
  description: 姓名${default.name},年龄${default.age}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gsms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: jinshoucai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true